version: '3.2.20'
services:
  app:
    build:
      volumes:
         - .:/django
      ports:
        -8000:8000
      image: social_networking_app:django
      container_name : django_container
      command: python manage.py runserver 0.0.0.0:8000
